appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default, win: azure}
travis:
  secure: {BINSTAR_TOKEN: ZlLdri2+1x9Ce3f+zkxMx6lqYGVv6+9hyTbSsSTy8HUk7zHFfGYSpalsncdpcHUHNA78AjdxmnG3zu75Ssle3HB0LD0Lhzg4FmaF4CxubkmefgtA6J6ULRiuca6SXV9yMo8mkOGyK4veYj4Tocn+rPPtdwK8NjFd6Jo6fPNfm44M96Wjg+aCbjyxCSWlFW6z1dOpRTVwDps8JVu8moSU0R1mIN22Eblux3/bldh5VKsNRFl7jahgjKOrZgzZ7SnNeelYRrC8u1JZ46wmECxnWTddmKTRU6gyOjB1kRevA0t9sUtunkUGqnm+uWeoN6/0Hdoi2B/J9grYrEoSIVBP3N8WWKCVHJ6LH43wG801AC0IVklJ8HDan+K+Fm3xMg3YBGcEiEs5yprZ0lvGAd5AmWwRSjUHJ4CJfKyZoF5zE8b7wCFufAIEszbroYmyE4lNLlIRcOhC0r2eo5xM2n3k4/mbsulzapC2QjrF7l3Z0hSj1aDtOfdzP4LNDPVCJtTEGMsWeP3Ex8/BMRF/yXiC+aGdjkUdspiQTRcTG3Q3nrYVFYXHopm06hRcxhBFhOiU+IHODRa8a5HCAbYcQJW8UFax5aJKfUQ1dwengZk/u62EtIg/z9t2Rja4jSRkb9nltZT0m1lZ+QSl3fzE5klL7alg9qbJZQ0Tg7haMpY08UM=}
